# ==========================================
# CONFIGURAÇÃO DE SERVIDOR WEB
# ==========================================
# O Render define a porta automaticamente através da variável PORT.
# Caso rode localmente, ele usará a 8080 por padrão.
server.port=${PORT:8080}

# ==========================================
# CONEXÃO COM O BANCO DE DADOS (PostgreSQL / Render)
# ==========================================
# Lê as variáveis de ambiente que configuraremos no painel do Render.
# Se não existirem, usará os valores locais como fallback.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_contatos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# Define a sintaxe do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 'update' cria ou atualiza automaticamente as tabelas no PostgreSQL da nuvem assim que o backend subir!
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL no log do Render para acompanhar o que está acontecendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true