# ==========================================
# Nome da aplicação
# ==========================================
spring.application.name=backend

# ==========================================
# Banco de Dados
# (configuraremos depois)
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/livrodb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Porta
# ==========================================
server.port=${PORT:8080}